In [4]:
import numpy as np 

In [34]:
a = np.array([[1,2],[3,4,]])
b = np.array([[5,6],[7,8]])
# sumc = a+b
# print(sumc)
sum_matrix = []
for i in range(len(a)):
    row = []
    for j in range(len(a[0])):
        row.append(a[i][j] + b[i][j])
    sum_matrix.append(row)
        
for row in sum_matrix:
    print(row)

[6, 8]
[10, 12]


In [35]:
# print(np.matmul(a,b))
mul_matrix = []
for i in range(len(a)):
    row = []
    for j in range(len(b[0])):
        ele = 0
        for k in range(len(b)):
            ele +=a[i][k] * b[k][j]
        row.append(ele)
    mul_matrix.append(row)

for row in mul_matrix:
    print(row)    

[19, 22]
[43, 50]


In [47]:
# scalarmul = 10*a
# print(scalarmul)
for i in range(len(a)):
    for j in range(len(a[0])):
        a[i][j] = 10*a[i][j]

for row in a:
    print(row)

[100 200]
[300 400]


In [58]:
v = np.array([1, 2])
np.dot(a,v)

res = []
for row in a:
    row_sum = 0
    for i in range(len(v)):
        row_sum += row[i] * v[i]
    res.append(row_sum)
print(res)

############################

matrix = [[1, 2],
          [3, 4]]
vector = [[5],
          [6]]
dot_product = [[0],
               [0]]

for i in range(len(matrix)):
    for j in range(len(vector[0])):
        for k in range(len(vector)):
            dot_product[i][j] += matrix[i][k] * vector[k][j]

print("Dot product:")
for row in dot_product:
    print(row)

[5, 11]
Dot product:
[17]
[39]


In [64]:
tmatrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
# np.transpose(tmatrix)
t=[]
for i in range(len(tmatrix)):
    tr=[]
    for j in range(len(tmatrix[0])):
        tr.append(tmatrix[i][j])
    t.append(tr)
for i in tmatrix:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
