In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3])
print(a)
a.size

[1 2 3]


3

In [13]:
b = np.array([[2,3,4],[2,4,5]])
print(b)
b.size

[[2 3 4]
 [2 4 5]]


6

In [14]:
#get dimensions (1d,2d)
# b.ndim
a.ndim

1

In [19]:
a.shape
#gives dimensions of array,
#consist of one ele=>length of the arr

(3,)

In [11]:
b.shape
#(rows,cols)

(2, 3)

In [20]:
#get type
# a.dtype
b.dtype

dtype('int32')

In [24]:
#can declare type also 
c = np.array([2,3.3],dtype='int')
c.dtype
print(c)

[2 3]


In [29]:
c.itemsize

4

In [34]:
#get total size
a.size* a.itemsize
#or simply
a.nbytes

12

In [38]:
d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d.shape

(2, 5)

In [44]:
#get particular indexes: 
d[1,4] 
#is same as
d[1,-1]

10

In [48]:
#get specific row
d[0,:]

array([1, 2, 3, 4, 5])

In [55]:
#get specific col
d[:,3]

array([4, 9])

In [52]:
#start index:endindex:stepsize
d[0,1:6:2]

array([2, 4])

In [57]:
d[1,1:-1:2]

array([7, 9])

In [63]:
#can change elements
d[1,0]=20
print(d)
d[:,2]=5  #for entire column
print(d)
d[:,3] = [0,0]
print(d)

[[ 1  2  5  4  5]
 [20  7  5  9 10]]
[[ 1  2  5  4  5]
 [20  7  5  9 10]]
[[ 1  2  5  0  5]
 [20  7  5  0 10]]


In [65]:
#all 0s matrix
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
#all 1s matrix
np.ones((4,2,2),dtype=int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
#any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [69]:
#full_like method; 
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [70]:
#random decimal num(0&1)
np.random.rand(2,1)

array([[0.54333573],
       [0.99036775]])

In [80]:
#random int values
np.random.randint(3,size=(2,2))

array([[2, 0],
       [2, 2]])

In [82]:
np.random.randint(2,8,size=(2,2))

array([[2, 4],
       [6, 4]])

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
#repeat an array
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [94]:
#copy 
m = np.array([1,2,3])
n = m.copy()
n[0]=4
print(n)

[4 2 3]


# Mathematics

In [95]:
g = np.array([3,4,5])
print(g)

[3 4 5]


In [96]:
g+1


array([4, 5, 6])

In [97]:
g-1

array([2, 3, 4])

In [98]:
g*2

array([ 6,  8, 10])

In [100]:
np.sin(g)

array([ 0.14112001, -0.7568025 , -0.95892427])